/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrn.gui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author letic
 */
public class Dashboard extends javax.swing.JFrame {

    DefaultTableModel modelo;
    
    public Dashboard() {
        
        initComponents();
        estilizarBtns();
        modelo = (DefaultTableModel) tableComprasDoMes.getModel();
        this.setExtendedState(6);
        header.setBackground(Color.decode("#343A40"));
        sideMenu.setBackground(Color.decode("#212529"));
        tableComprasDoMesLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("#CFCFCF")));
        tableComprasDoMesLabel.setOpaque(true);
        tableComprasDoMes.setBorder(null);
        scrollTableComprasDoMes.setBorder(null);
        tableComprasDoMes.setFillsViewportHeight(true);
        JTableHeader tableComprasDoMesHeader = tableComprasDoMes.getTableHeader();
        tableComprasDoMesHeader.setFont((new Font("Raleway", 0, 13)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrap = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        headerIcon = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        sideMenu = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        dashboardLabel = new javax.swing.JLabel();
        dashboardDivisor = new javax.swing.JSeparator();
        comprasDoMes = new javax.swing.JPanel();
        comprasDoMesDivisor = new javax.swing.JSeparator();
        comprasDoMesNumber = new javax.swing.JLabel();
        comprasDoMesLabel = new javax.swing.JLabel();
        comprasDoMesDetalhar = new javax.swing.JLabel();
        comprasDoMesBtn = new javax.swing.JLabel();
        notificacoes = new javax.swing.JPanel();
        notificacoesDivisor = new javax.swing.JSeparator();
        notificacoesNumber = new javax.swing.JLabel();
        notificacoesLabel = new javax.swing.JLabel();
        notificacoesDetalhar = new javax.swing.JLabel();
        notificacoesBtn = new javax.swing.JLabel();
        produtosCadastrados = new javax.swing.JPanel();
        produtosCadastradosDivisor = new javax.swing.JSeparator();
        produtosCadastradosNumber = new javax.swing.JLabel();
        produtosCadastradosLabel = new javax.swing.JLabel();
        produtosCadastradosDetalhar = new javax.swing.JLabel();
        produtosCadastradosBtn = new javax.swing.JLabel();
        fornecedoresCadastrados = new javax.swing.JPanel();
        fornecedoresCadastradosDivisor = new javax.swing.JSeparator();
        fornecedoresCadastradosNumber = new javax.swing.JLabel();
        fornecedoresCadastradosLabel = new javax.swing.JLabel();
        fornecedoresCadastradosDetalhar = new javax.swing.JLabel();
        fornecedoresCadastradosBtn = new javax.swing.JLabel();
        wrapTableComprasDoMes = new javax.swing.JPanel();
        tableComprasDoMesLabel = new javax.swing.JLabel();
        scrollTableComprasDoMes = new javax.swing.JScrollPane();
        tableComprasDoMes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(960, 574));
        setUndecorated(true);

        wrap.setBackground(new java.awt.Color(255, 255, 255));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/fechar.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        headerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/headerIcon.png"))); // NOI18N

        headerLabel.setFont(new java.awt.Font("Raleway Medium", 0, 15)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("INVENTARY MANAGER");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnDashboardFocus.png"))); // NOI18N
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnCompras.png"))); // NOI18N
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnProdutos.png"))); // NOI18N
        btnProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btbFornecedores.png"))); // NOI18N
        btnFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFornecedores)
                    .addComponent(btnCompras)
                    .addComponent(btnDashboard)
                    .addComponent(btnProdutos))
                .addGap(0, 65, Short.MAX_VALUE))
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dashboardLabel.setFont(new java.awt.Font("Raleway", 0, 30)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(33, 33, 33));
        dashboardLabel.setText("Dashboard");

        dashboardDivisor.setForeground(new java.awt.Color(168, 168, 168));

        comprasDoMes.setBackground(new java.awt.Color(0, 119, 247));
        comprasDoMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 104, 216)));

        comprasDoMesDivisor.setBackground(new java.awt.Color(0, 104, 216));
        comprasDoMesDivisor.setForeground(new java.awt.Color(0, 104, 216));

        comprasDoMesNumber.setFont(new java.awt.Font("Raleway SemiBold", 0, 22)); // NOI18N
        comprasDoMesNumber.setForeground(new java.awt.Color(255, 255, 255));
        comprasDoMesNumber.setText("12");

        comprasDoMesLabel.setBackground(new java.awt.Color(255, 255, 255));
        comprasDoMesLabel.setFont(new java.awt.Font("Raleway Medium", 0, 18)); // NOI18N
        comprasDoMesLabel.setForeground(new java.awt.Color(255, 255, 255));
        comprasDoMesLabel.setText("Compras");

        comprasDoMesDetalhar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/arrowRight.png"))); // NOI18N

        comprasDoMesBtn.setBackground(new java.awt.Color(255, 255, 255));
        comprasDoMesBtn.setFont(new java.awt.Font("Raleway Medium", 0, 12)); // NOI18N
        comprasDoMesBtn.setForeground(new java.awt.Color(255, 255, 255));
        comprasDoMesBtn.setText("Mais detalhes");
        comprasDoMesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprasDoMesBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout comprasDoMesLayout = new javax.swing.GroupLayout(comprasDoMes);
        comprasDoMes.setLayout(comprasDoMesLayout);
        comprasDoMesLayout.setHorizontalGroup(
            comprasDoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comprasDoMesDivisor)
            .addGroup(comprasDoMesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(comprasDoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comprasDoMesLabel)
                    .addComponent(comprasDoMesNumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comprasDoMesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comprasDoMesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comprasDoMesDetalhar)
                .addContainerGap())
        );
        comprasDoMesLayout.setVerticalGroup(
            comprasDoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comprasDoMesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(comprasDoMesNumber)
                .addGap(4, 4, 4)
                .addComponent(comprasDoMesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(comprasDoMesDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(comprasDoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comprasDoMesDetalhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comprasDoMesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        notificacoes.setBackground(new java.awt.Color(220, 53, 69));
        notificacoes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 46, 60), 1, true));

        notificacoesDivisor.setBackground(new java.awt.Color(192, 46, 60));
        notificacoesDivisor.setForeground(new java.awt.Color(192, 46, 60));

        notificacoesNumber.setFont(new java.awt.Font("Raleway SemiBold", 0, 22)); // NOI18N
        notificacoesNumber.setForeground(new java.awt.Color(255, 255, 255));
        notificacoesNumber.setText("2");

        notificacoesLabel.setBackground(new java.awt.Color(255, 255, 255));
        notificacoesLabel.setFont(new java.awt.Font("Raleway Medium", 0, 18)); // NOI18N
        notificacoesLabel.setForeground(new java.awt.Color(255, 255, 255));
        notificacoesLabel.setText("Compras");

        notificacoesDetalhar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/arrowRight.png"))); // NOI18N

        notificacoesBtn.setBackground(new java.awt.Color(255, 255, 255));
        notificacoesBtn.setFont(new java.awt.Font("Raleway Medium", 0, 12)); // NOI18N
        notificacoesBtn.setForeground(new java.awt.Color(255, 255, 255));
        notificacoesBtn.setText("Mais detalhes");
        notificacoesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificacoesBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout notificacoesLayout = new javax.swing.GroupLayout(notificacoes);
        notificacoes.setLayout(notificacoesLayout);
        notificacoesLayout.setHorizontalGroup(
            notificacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notificacoesDivisor)
            .addGroup(notificacoesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(notificacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notificacoesLabel)
                    .addComponent(notificacoesNumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notificacoesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notificacoesDetalhar)
                .addContainerGap())
        );
        notificacoesLayout.setVerticalGroup(
            notificacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificacoesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(notificacoesNumber)
                .addGap(4, 4, 4)
                .addComponent(notificacoesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(notificacoesDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(notificacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(notificacoesDetalhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notificacoesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        produtosCadastrados.setBackground(new java.awt.Color(39, 162, 67));
        produtosCadastrados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 140, 58)));

        produtosCadastradosDivisor.setBackground(new java.awt.Color(34, 140, 58));
        produtosCadastradosDivisor.setForeground(new java.awt.Color(34, 140, 58));

        produtosCadastradosNumber.setFont(new java.awt.Font("Raleway SemiBold", 0, 22)); // NOI18N
        produtosCadastradosNumber.setForeground(new java.awt.Color(255, 255, 255));
        produtosCadastradosNumber.setText("107");

        produtosCadastradosLabel.setBackground(new java.awt.Color(255, 255, 255));
        produtosCadastradosLabel.setFont(new java.awt.Font("Raleway Medium", 0, 18)); // NOI18N
        produtosCadastradosLabel.setForeground(new java.awt.Color(255, 255, 255));
        produtosCadastradosLabel.setText("Compras");

        produtosCadastradosDetalhar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/arrowRight.png"))); // NOI18N

        produtosCadastradosBtn.setBackground(new java.awt.Color(255, 255, 255));
        produtosCadastradosBtn.setFont(new java.awt.Font("Raleway Medium", 0, 12)); // NOI18N
        produtosCadastradosBtn.setForeground(new java.awt.Color(255, 255, 255));
        produtosCadastradosBtn.setText("Mais detalhes");
        produtosCadastradosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtosCadastradosBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout produtosCadastradosLayout = new javax.swing.GroupLayout(produtosCadastrados);
        produtosCadastrados.setLayout(produtosCadastradosLayout);
        produtosCadastradosLayout.setHorizontalGroup(
            produtosCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(produtosCadastradosDivisor)
            .addGroup(produtosCadastradosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(produtosCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(produtosCadastradosLabel)
                    .addComponent(produtosCadastradosNumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtosCadastradosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(produtosCadastradosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produtosCadastradosDetalhar)
                .addContainerGap())
        );
        produtosCadastradosLayout.setVerticalGroup(
            produtosCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtosCadastradosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(produtosCadastradosNumber)
                .addGap(4, 4, 4)
                .addComponent(produtosCadastradosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(produtosCadastradosDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(produtosCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(produtosCadastradosDetalhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(produtosCadastradosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        fornecedoresCadastrados.setBackground(new java.awt.Color(247, 187, 7));
        fornecedoresCadastrados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 163, 6)));

        fornecedoresCadastradosDivisor.setBackground(new java.awt.Color(216, 163, 6));
        fornecedoresCadastradosDivisor.setForeground(new java.awt.Color(216, 163, 6));

        fornecedoresCadastradosNumber.setFont(new java.awt.Font("Raleway SemiBold", 0, 22)); // NOI18N
        fornecedoresCadastradosNumber.setForeground(new java.awt.Color(255, 255, 255));
        fornecedoresCadastradosNumber.setText("8");

        fornecedoresCadastradosLabel.setBackground(new java.awt.Color(255, 255, 255));
        fornecedoresCadastradosLabel.setFont(new java.awt.Font("Raleway Medium", 0, 18)); // NOI18N
        fornecedoresCadastradosLabel.setForeground(new java.awt.Color(255, 255, 255));
        fornecedoresCadastradosLabel.setText("Compras");

        fornecedoresCadastradosDetalhar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/arrowRight.png"))); // NOI18N

        fornecedoresCadastradosBtn.setBackground(new java.awt.Color(255, 255, 255));
        fornecedoresCadastradosBtn.setFont(new java.awt.Font("Raleway Medium", 0, 12)); // NOI18N
        fornecedoresCadastradosBtn.setForeground(new java.awt.Color(255, 255, 255));
        fornecedoresCadastradosBtn.setText("Mais detalhes");
        fornecedoresCadastradosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fornecedoresCadastradosBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fornecedoresCadastradosLayout = new javax.swing.GroupLayout(fornecedoresCadastrados);
        fornecedoresCadastrados.setLayout(fornecedoresCadastradosLayout);
        fornecedoresCadastradosLayout.setHorizontalGroup(
            fornecedoresCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fornecedoresCadastradosDivisor)
            .addGroup(fornecedoresCadastradosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(fornecedoresCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fornecedoresCadastradosLabel)
                    .addComponent(fornecedoresCadastradosNumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fornecedoresCadastradosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fornecedoresCadastradosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fornecedoresCadastradosDetalhar)
                .addContainerGap())
        );
        fornecedoresCadastradosLayout.setVerticalGroup(
            fornecedoresCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fornecedoresCadastradosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(fornecedoresCadastradosNumber)
                .addGap(4, 4, 4)
                .addComponent(fornecedoresCadastradosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(fornecedoresCadastradosDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(fornecedoresCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fornecedoresCadastradosDetalhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fornecedoresCadastradosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        wrapTableComprasDoMes.setBackground(new java.awt.Color(255, 255, 255));
        wrapTableComprasDoMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207)));

        tableComprasDoMesLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tableComprasDoMesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/tableComprasHeaderIcon.png"))); // NOI18N
        tableComprasDoMesLabel.setText("Compras deste mês");

        tableComprasDoMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableComprasDoMes.setGridColor(new java.awt.Color(255, 255, 255));
        tableComprasDoMes.setRowHeight(24);
        scrollTableComprasDoMes.setViewportView(tableComprasDoMes);

        javax.swing.GroupLayout wrapTableComprasDoMesLayout = new javax.swing.GroupLayout(wrapTableComprasDoMes);
        wrapTableComprasDoMes.setLayout(wrapTableComprasDoMesLayout);
        wrapTableComprasDoMesLayout.setHorizontalGroup(
            wrapTableComprasDoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableComprasDoMesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollTableComprasDoMes, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        wrapTableComprasDoMesLayout.setVerticalGroup(
            wrapTableComprasDoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapTableComprasDoMesLayout.createSequentialGroup()
                .addComponent(tableComprasDoMesLabel)
                .addGap(0, 0, 0)
                .addComponent(scrollTableComprasDoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout wrapLayout = new javax.swing.GroupLayout(wrap);
        wrap.setLayout(wrapLayout);
        wrapLayout.setHorizontalGroup(
            wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(wrapLayout.createSequentialGroup()
                .addComponent(sideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addComponent(dashboardLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addComponent(comprasDoMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(notificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(produtosCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(fornecedoresCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(wrapTableComprasDoMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardDivisor))
                .addGap(30, 30, 30))
        );
        wrapLayout.setVerticalGroup(
            wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(notificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(wrapLayout.createSequentialGroup()
                                .addComponent(dashboardLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dashboardDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comprasDoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(produtosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fornecedoresCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(wrapTableComprasDoMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprasDoMesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprasDoMesBtnMouseClicked
        
    }//GEN-LAST:event_comprasDoMesBtnMouseClicked

    private void notificacoesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificacoesBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_notificacoesBtnMouseClicked

    private void produtosCadastradosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtosCadastradosBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_produtosCadastradosBtnMouseClicked

    private void fornecedoresCadastradosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fornecedoresCadastradosBtnMouseClicked
        
    }//GEN-LAST:event_fornecedoresCadastradosBtnMouseClicked

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        new Produtos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
        new Fornecedores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    
    private void estilizarBtns(){
        btnDashboard.setOpaque(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setFocusPainted(false);
        
        btnCompras.setOpaque(false);
        btnCompras.setContentAreaFilled(false);
        btnCompras.setBorderPainted(false);
        btnCompras.setFocusPainted(false);
        
        btnProdutos.setOpaque(false);
        btnProdutos.setContentAreaFilled(false);
        btnProdutos.setBorderPainted(false);
        btnProdutos.setFocusPainted(false);
        
        btnFornecedores.setOpaque(false);
        btnFornecedores.setContentAreaFilled(false);
        btnFornecedores.setBorderPainted(false);
        btnFornecedores.setFocusPainted(false);
        
        btnExit.setFocusPainted(false);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JPanel comprasDoMes;
    private javax.swing.JLabel comprasDoMesBtn;
    private javax.swing.JLabel comprasDoMesDetalhar;
    private javax.swing.JSeparator comprasDoMesDivisor;
    private javax.swing.JLabel comprasDoMesLabel;
    private javax.swing.JLabel comprasDoMesNumber;
    private javax.swing.JSeparator dashboardDivisor;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JPanel fornecedoresCadastrados;
    private javax.swing.JLabel fornecedoresCadastradosBtn;
    private javax.swing.JLabel fornecedoresCadastradosDetalhar;
    private javax.swing.JSeparator fornecedoresCadastradosDivisor;
    private javax.swing.JLabel fornecedoresCadastradosLabel;
    private javax.swing.JLabel fornecedoresCadastradosNumber;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerIcon;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel notificacoes;
    private javax.swing.JLabel notificacoesBtn;
    private javax.swing.JLabel notificacoesDetalhar;
    private javax.swing.JSeparator notificacoesDivisor;
    private javax.swing.JLabel notificacoesLabel;
    private javax.swing.JLabel notificacoesNumber;
    private javax.swing.JPanel produtosCadastrados;
    private javax.swing.JLabel produtosCadastradosBtn;
    private javax.swing.JLabel produtosCadastradosDetalhar;
    private javax.swing.JSeparator produtosCadastradosDivisor;
    private javax.swing.JLabel produtosCadastradosLabel;
    private javax.swing.JLabel produtosCadastradosNumber;
    private javax.swing.JScrollPane scrollTableComprasDoMes;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JTable tableComprasDoMes;
    private javax.swing.JLabel tableComprasDoMesLabel;
    private javax.swing.JPanel wrap;
    private javax.swing.JPanel wrapTableComprasDoMes;
    // End of variables declaration//GEN-END:variables
}
