package br.edu.ifrn.gui;

import br.edu.ifrn.negocio.Fornecedor;
import br.edu.ifrn.negocio.Telefone;
import br.edu.ifrn.persistencia.FornecedorDAO;
import br.edu.ifrn.persistencia.TelefoneFornecedorDAO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Event;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class DetalharForncedor extends javax.swing.JFrame {

    DefaultTableModel modeloTableProdutosFornecedor;
    DefaultTableModel modeloTableTelefones;
    int mouseX;
    int mouseY;
    int selectedRow;
    int selectedColumn;
    boolean alteracoes;
    Fornecedor fornecedor;
    int countTelefone;

    public DetalharForncedor(String cnpj) {
        initComponents();
        modeloTableTelefones = (DefaultTableModel) tableTelefones.getModel();
        modeloTableProdutosFornecedor = (DefaultTableModel) tableProdutosFornecedor.getModel();
        inicializarDados(cnpj);
        estilizarComponentes();
        estilizarBtns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrap = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        headerIcon = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sideMenu = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fornecedorLabel = new javax.swing.JLabel();
        fornecedorDivisor = new javax.swing.JSeparator();
        wrapTableProdutosFornecedor = new javax.swing.JPanel();
        tableProdutosFornecedorLabel = new javax.swing.JLabel();
        scrollTableProdutosFornecedor = new javax.swing.JScrollPane();
        tableProdutosFornecedor = new javax.swing.JTable();
        cnpjLabel = new javax.swing.JLabel();
        cnpjField = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        telefonesLabel = new javax.swing.JLabel();
        btnSalvarAlteracoes = new javax.swing.JButton();
        btnExcluirTelefone = new javax.swing.JButton();
        tableTelefones = new javax.swing.JTable();
        novoTelefoneLabel = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnAdicionarTelefone = new javax.swing.JButton();
        novoTelefoneField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(960, 574));
        setUndecorated(true);

        wrap.setBackground(new java.awt.Color(255, 255, 255));
        wrap.setToolTipText("");

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/fechar.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        headerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/headerIcon.png"))); // NOI18N

        headerLabel.setFont(new java.awt.Font("Raleway Medium", 0, 15)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("INVENTARY MANAGER");

        jButton1.setText("jButton1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerLabel)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerLabel)
                    .addComponent(jLabel2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnDashboard.png"))); // NOI18N
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnCompras.png"))); // NOI18N
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnProdutos.png"))); // NOI18N
        btnProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btbFornecedoresFocus.png"))); // NOI18N
        btnFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedoresActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideMenuLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFornecedores)
                            .addComponent(btnCompras)
                            .addComponent(btnDashboard)
                            .addComponent(btnProdutos)))
                    .addGroup(sideMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(0, 65, Short.MAX_VALUE))
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        fornecedorLabel.setFont(new java.awt.Font("Raleway", 0, 26)); // NOI18N
        fornecedorLabel.setForeground(new java.awt.Color(33, 33, 33));
        fornecedorLabel.setText("Fornecedores/Nome do fornecedor");

        fornecedorDivisor.setForeground(new java.awt.Color(168, 168, 168));

        wrapTableProdutosFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        wrapTableProdutosFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207)));

        tableProdutosFornecedorLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tableProdutosFornecedorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/tableComprasHeaderIcon.png"))); // NOI18N
        tableProdutosFornecedorLabel.setText("Fornecedores cadastrados");

        tableProdutosFornecedor.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        tableProdutosFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CNPJ", "Nome", "Email", "Telefones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProdutosFornecedor.setGridColor(new java.awt.Color(255, 255, 255));
        tableProdutosFornecedor.setRowHeight(24);
        tableProdutosFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdutosFornecedorMouseClicked(evt);
            }
        });
        scrollTableProdutosFornecedor.setViewportView(tableProdutosFornecedor);
        if (tableProdutosFornecedor.getColumnModel().getColumnCount() > 0) {
            tableProdutosFornecedor.getColumnModel().getColumn(0).setResizable(false);
            tableProdutosFornecedor.getColumnModel().getColumn(0).setHeaderValue("CNPJ");
            tableProdutosFornecedor.getColumnModel().getColumn(2).setHeaderValue("Email");
            tableProdutosFornecedor.getColumnModel().getColumn(3).setHeaderValue("Telefones");
        }

        javax.swing.GroupLayout wrapTableProdutosFornecedorLayout = new javax.swing.GroupLayout(wrapTableProdutosFornecedor);
        wrapTableProdutosFornecedor.setLayout(wrapTableProdutosFornecedorLayout);
        wrapTableProdutosFornecedorLayout.setHorizontalGroup(
            wrapTableProdutosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableProdutosFornecedorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollTableProdutosFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        wrapTableProdutosFornecedorLayout.setVerticalGroup(
            wrapTableProdutosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapTableProdutosFornecedorLayout.createSequentialGroup()
                .addComponent(tableProdutosFornecedorLabel)
                .addGap(0, 0, 0)
                .addComponent(scrollTableProdutosFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        cnpjLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        cnpjLabel.setForeground(new java.awt.Color(34, 34, 34));
        cnpjLabel.setText("CNPJ:");

        cnpjField.setEditable(false);
        cnpjField.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N

        nomeLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(34, 34, 34));
        nomeLabel.setText("Nome:");

        nomeField.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        nomeField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nomeFieldCaretUpdate(evt);
            }
        });

        emailField.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        emailField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                emailFieldCaretUpdate(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(34, 34, 34));
        emailLabel.setText("Email:");

        telefonesLabel.setFont(new java.awt.Font("Raleway SemiBold", 0, 16)); // NOI18N
        telefonesLabel.setForeground(new java.awt.Color(34, 34, 34));
        telefonesLabel.setText("Telefone(s)");

        btnSalvarAlteracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/salvarAlteracoes.png"))); // NOI18N
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });

        btnExcluirTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/excluirTelefone.png"))); // NOI18N
        btnExcluirTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTelefoneActionPerformed(evt);
            }
        });

        tableTelefones.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        tableTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4", "Título 5", "Título 6", "Título 7"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    tableTelefones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    tableTelefones.setGridColor(new java.awt.Color(207, 207, 207));
    tableTelefones.setRowHeight(35);
    tableTelefones.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tableTelefonesMouseClicked(evt);
        }
    });

    novoTelefoneLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
    novoTelefoneLabel.setText("Novo telefone");

    btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/voltar.png"))); // NOI18N
    btnVoltar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnVoltarActionPerformed(evt);
        }
    });

    btnAdicionarTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/adicionarTelefone.png"))); // NOI18N
    btnAdicionarTelefone.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAdicionarTelefoneActionPerformed(evt);
        }
    });

    try {
        novoTelefoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }

    javax.swing.GroupLayout wrapLayout = new javax.swing.GroupLayout(wrap);
    wrap.setLayout(wrapLayout);
    wrapLayout.setHorizontalGroup(
        wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(wrapLayout.createSequentialGroup()
            .addComponent(sideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(30, 30, 30)
            .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wrapLayout.createSequentialGroup()
                    .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(wrapLayout.createSequentialGroup()
                            .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cnpjLabel)
                                .addComponent(cnpjField))
                            .addGap(21, 21, 21)
                            .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeField)
                                .addGroup(wrapLayout.createSequentialGroup()
                                    .addComponent(nomeLabel)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(22, 22, 22)
                            .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailLabel)
                                .addComponent(emailField))
                            .addGap(1, 1, 1))
                        .addComponent(fornecedorDivisor)
                        .addComponent(wrapTableProdutosFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(wrapLayout.createSequentialGroup()
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fornecedorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                            .addGap(77, 77, 77)))
                    .addGap(30, 30, 30))
                .addGroup(wrapLayout.createSequentialGroup()
                    .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnExcluirTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalvarAlteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(wrapLayout.createSequentialGroup()
                            .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telefonesLabel)
                                .addComponent(tableTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(wrapLayout.createSequentialGroup()
                                    .addComponent(novoTelefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAdicionarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(novoTelefoneLabel))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    wrapLayout.setVerticalGroup(
        wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(wrapLayout.createSequentialGroup()
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(sideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(wrapLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fornecedorLabel)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fornecedorDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(wrapLayout.createSequentialGroup()
                                .addComponent(cnpjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cnpjField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(wrapLayout.createSequentialGroup()
                                .addComponent(nomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(wrapLayout.createSequentialGroup()
                            .addComponent(emailLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(9, 9, 9)
                    .addComponent(btnSalvarAlteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(telefonesLabel)
                        .addComponent(novoTelefoneLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAdicionarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tableTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(novoTelefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(btnExcluirTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)
                    .addComponent(wrapTableProdutosFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(43, 43, 43))))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(wrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(wrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if (alteracoes) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fechar o programa? Existem alterações não salvas", "AVISO", dialogButton);
            if (resultado == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fechar o programa?", "AVISO", dialogButton);
            if (resultado == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        if (alteracoes) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair desta página? Existem alterações não salvas", "AVISO", dialogButton);
            if (resultado == JOptionPane.YES_OPTION) {
                new Dashboard().setVisible(true);
                this.dispose();
            }
        } else {
            new Dashboard().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        if (alteracoes) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair desta página? Existem alterações não salvas", "AVISO", dialogButton);
            if (resultado == JOptionPane.YES_OPTION) {
                new Produtos().setVisible(true);
                this.dispose();
            }
        } else {
            new Produtos().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
        if (alteracoes) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair desta página? Existem alterações não salvas", "AVISO", dialogButton);
            if (resultado == JOptionPane.YES_OPTION) {
                new Fornecedores().setVisible(true);
                this.dispose();
            }
        } else {
            new Fornecedores().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void tableProdutosFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutosFornecedorMouseClicked
        if (evt.getClickCount() != 0) {
            selectedRow = tableProdutosFornecedor.getSelectedRow();
            //this.btnExcluir.setVisible(true);

            if (evt.getClickCount() >= 2) {

            }
        }
    }//GEN-LAST:event_tableProdutosFornecedorMouseClicked

    private void nomeFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nomeFieldCaretUpdate
        if (!nomeField.getText().equals(fornecedor.getNome()) || !emailField.getText().equals(fornecedor.getEmail())) {
            this.btnSalvarAlteracoes.setVisible(true);
            this.alteracoes = true;
        } else {
            this.btnSalvarAlteracoes.setVisible(false);
            this.alteracoes = false;
        }
    }//GEN-LAST:event_nomeFieldCaretUpdate

    private void emailFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_emailFieldCaretUpdate
        if (!emailField.getText().equals(fornecedor.getEmail()) || !nomeField.getText().equals(fornecedor.getNome())) {
            this.btnSalvarAlteracoes.setVisible(true);
            this.alteracoes = true;
        } else {
            this.btnSalvarAlteracoes.setVisible(false);
            this.alteracoes = false;
        }
    }//GEN-LAST:event_emailFieldCaretUpdate

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja realizar as alterações?", "AVISO", dialogButton);
        if (resultado == JOptionPane.YES_OPTION) {
            String nome = nomeField.getText();
            String cnpj = this.fornecedor.getCnpj();
            String email = emailField.getText();
            new FornecedorDAO().updateFornecedor(nome, email, cnpj);
            btnSalvarAlteracoes.setVisible(false);
            inicializarDados(this.fornecedor.getCnpj());
            this.alteracoes = false;
        }
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void tableTelefonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTelefonesMouseClicked
        if (new TelefoneFornecedorDAO().getTelefoneCount(this.fornecedor.getCnpj()) > 1) {
            selectedColumn = tableTelefones.getSelectedColumn();
            btnExcluirTelefone.setVisible(true);
        }
    }//GEN-LAST:event_tableTelefonesMouseClicked

    private void btnExcluirTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTelefoneActionPerformed
        String telefone = (String) tableTelefones.getValueAt(0, selectedColumn);
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null, "Tem certeza deseja excluir o número de telefone" + "", "AVISO", dialogButton);
        if (resultado == JOptionPane.YES_OPTION) {
            new TelefoneFornecedorDAO().deletarTelefoneFornecedor(this.fornecedor.getCnpj(), telefone);
            setTelefones(this.fornecedor.getCnpj());
            btnExcluirTelefone.setVisible(false);
        }
    }//GEN-LAST:event_btnExcluirTelefoneActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if (alteracoes) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair desta página? Existem alterações não salvas", "AVISO", dialogButton);
            if (resultado == JOptionPane.YES_OPTION) {
                new Fornecedores().setVisible(true);
                this.dispose();
            }
        } else {
            new Fornecedores().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAdicionarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTelefoneActionPerformed
        if (new TelefoneFornecedorDAO().verificarTelefone(novoTelefoneField.getText())) {
            new TelefoneFornecedorDAO().cadastrarTelefoneFornecedor(novoTelefoneField.getText(), this.fornecedor.getCnpj());
            setTelefones(this.fornecedor.getCnpj());
        } else {
            JOptionPane.showMessageDialog(null, "Este número de já foi cadastrado");
        }
    }//GEN-LAST:event_btnAdicionarTelefoneActionPerformed

    private void setTelefones(String cnpj) {
        modeloTableTelefones.setColumnCount(0);
        for (Telefone t : new TelefoneFornecedorDAO().selecionarTelefones(cnpj)) {
            modeloTableTelefones.addColumn("", new Object[]{t.getTelefone()});
        }
        for (int i = 0; i < modeloTableTelefones.getColumnCount(); i++) {
            tableTelefones.getColumnModel().getColumn(i).setPreferredWidth(110);
            tableTelefones.getColumnModel().getColumn(i).setMinWidth(110);
            tableTelefones.getColumnModel().getColumn(i).setMaxWidth(110);
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(JLabel.CENTER);
            tableTelefones.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
        }
        if (new TelefoneFornecedorDAO().getTelefoneCount(cnpj) >= 9) {
            novoTelefoneField.setVisible(false);
            btnAdicionarTelefone.setVisible(false);
            novoTelefoneLabel.setVisible(false);
        } else {
            novoTelefoneField.setVisible(true);
            btnAdicionarTelefone.setVisible(true);
            novoTelefoneLabel.setVisible(true);
        }

        if (new TelefoneFornecedorDAO().getTelefoneCount(cnpj) == 1) {

        }

    }

    /*
    private void selecionar() {
        modeloTableProdutosFornecedor.setNumRows(0);
        for (Fornecedor f : new FornecedorDAO().selecionarFornecedores()) {
            modeloTableProdutosFornecedor.addRow(new Object[]{"  " + f.getCnpj(), "  " + f.getNome(), "  " + f.getEmail(), "  " + new TelefoneFornecedorDAO().selectTelefonesJuntos(f.getCnpj())});
        }
    }

    private void selecionarComRest() {
        modeloTableProdutosFornecedor.setNumRows(0);
        for (Fornecedor f : new FornecedorDAO().selecionarFornecedores()) {
            modeloTableProdutosFornecedor.addRow(new Object[]{"  " + f.getCnpj(), "  " + f.getNome(), "  " + f.getEmail(), "  " + new TelefoneFornecedorDAO().selectTelefonesJuntos(f.getCnpj())});
        }
    }
     */
    private void estilizarComponentes() {
        this.setExtendedState(6);
        tableTelefones.setRowSelectionAllowed(false);
        header.setBackground(Color.decode("#343A40"));
        sideMenu.setBackground(Color.decode("#212529"));
        tableProdutosFornecedorLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("#CFCFCF")));
        tableProdutosFornecedorLabel.setOpaque(true);
        tableProdutosFornecedor.setBorder(null);
        scrollTableProdutosFornecedor.setBorder(null);
        tableProdutosFornecedor.setFillsViewportHeight(true);
        JTableHeader tableComprasDoMesHeader = tableProdutosFornecedor.getTableHeader();
        tableComprasDoMesHeader.setFont((new Font("Raleway SemiBold", 0, 13)));
        cnpjField.setBorder(BorderFactory.createCompoundBorder(cnpjField.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        nomeField.setBorder(BorderFactory.createCompoundBorder(nomeField.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        emailField.setBorder(BorderFactory.createCompoundBorder(emailField.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        tableTelefones.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.decode("#CFCFCF")));
    }

    private void estilizarBtns() {
        btnSalvarAlteracoes.setVisible(false);
        btnExcluirTelefone.setVisible(false);

        btnDashboard.setFocusPainted(false);
        btnProdutos.setFocusPainted(false);
        btnFornecedores.setFocusPainted(false);
        btnCompras.setFocusPainted(false);
        btnExit.setFocusPainted(false);
        btnSalvarAlteracoes.setFocusPainted(false);
        btnExcluirTelefone.setFocusPainted(false);
        btnVoltar.setFocusPainted(false);

        btnCompras.setOpaque(false);
        btnProdutos.setOpaque(false);
        btnFornecedores.setOpaque(false);
        btnDashboard.setOpaque(false);
        btnVoltar.setOpaque(false);

        btnFornecedores.setBorderPainted(false);
        btnDashboard.setBorderPainted(false);
        btnCompras.setBorderPainted(false);
        btnProdutos.setBorderPainted(false);
        btnVoltar.setBorderPainted(false);

        btnFornecedores.setContentAreaFilled(false);
        btnDashboard.setContentAreaFilled(false);
        btnCompras.setContentAreaFilled(false);
        btnProdutos.setContentAreaFilled(false);
        btnVoltar.setContentAreaFilled(false);
    }

    public void inicializarDados(String cnpj) {
        setTelefones(cnpj);
        //selecionar();
        fornecedor = new FornecedorDAO().toFornecedor(cnpj);
        nomeField.setText(this.fornecedor.getNome());
        emailField.setText(this.fornecedor.getEmail());
        cnpjField.setText(this.fornecedor.getCnpj());
        fornecedorLabel.setText("Fornecedores / " + " " + fornecedor.getNome());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalharForncedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalharForncedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalharForncedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalharForncedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalharForncedor("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarTelefone;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnExcluirTelefone;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField cnpjField;
    private javax.swing.JLabel cnpjLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JSeparator fornecedorDivisor;
    private javax.swing.JLabel fornecedorLabel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerIcon;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JFormattedTextField novoTelefoneField;
    private javax.swing.JLabel novoTelefoneLabel;
    private javax.swing.JScrollPane scrollTableProdutosFornecedor;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JTable tableProdutosFornecedor;
    private javax.swing.JLabel tableProdutosFornecedorLabel;
    private javax.swing.JTable tableTelefones;
    private javax.swing.JLabel telefonesLabel;
    private javax.swing.JPanel wrap;
    private javax.swing.JPanel wrapTableProdutosFornecedor;
    // End of variables declaration//GEN-END:variables
}
