/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrn.gui;

import br.edu.ifrn.negocio.Fornecedor;
import br.edu.ifrn.persistencia.FornecedorDAO;
import br.edu.ifrn.persistencia.TelefoneFornecedorDAO;
import java.awt.Color;
import java.awt.Font;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author letic
 */
public class Fornecedores extends javax.swing.JFrame {

    DefaultTableModel modelo;
    int mouseX;
    int mouseY;
    int selectedRow;

    public Fornecedores() {

        initComponents();
        estilizarBtns();
        estilizarComponentes();
        modelo = (DefaultTableModel) tableFornecedores.getModel();
        selecionar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarFornecedor = new javax.swing.JDialog();
        wrapCadastrarFornecedor = new javax.swing.JPanel();
        cadastrarFornecedorHeader = new javax.swing.JLabel();
        cadastrarFornecedorCNPJLabel = new javax.swing.JLabel();
        cadastrarFornecedorNomeLabel = new javax.swing.JLabel();
        cadastrarFornecedorNome = new javax.swing.JTextField();
        cadastrarFornecedorEmailLabel = new javax.swing.JLabel();
        cadastrarFornecedorEmail = new javax.swing.JTextField();
        cadastrarFornecedorTelefoneLabel = new javax.swing.JLabel();
        cadastrarFornecedorTelefoneOpcionalLabel = new javax.swing.JLabel();
        cadastrarFornecedorBtnCancelar = new javax.swing.JButton();
        cadastrarFornecedorBtnCadastrar = new javax.swing.JButton();
        cadastrarFornecedorCNPJ = new javax.swing.JFormattedTextField();
        cadastrarFornecedorTelefone = new javax.swing.JFormattedTextField();
        cadastrarFornecedorTelefoneOpcional = new javax.swing.JFormattedTextField();
        wrap = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        headerIcon = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        sideMenu = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        fornecedoresLabel = new javax.swing.JLabel();
        fornecedoresDivisor = new javax.swing.JSeparator();
        wrapTableFornecedores = new javax.swing.JPanel();
        tableFornecedoresLabel = new javax.swing.JLabel();
        scrollTableFornecedores = new javax.swing.JScrollPane();
        tableFornecedores = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnCadastrarFornecedor = new javax.swing.JButton();
        instructions = new javax.swing.JLabel();
        pesquisaFornecedores = new javax.swing.JTextField();

        cadastrarFornecedor.setMinimumSize(new java.awt.Dimension(352, 551));
        cadastrarFornecedor.setModal(true);
        cadastrarFornecedor.setUndecorated(true);

        wrapCadastrarFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        wrapCadastrarFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 162, 67)));
        wrapCadastrarFornecedor.setMaximumSize(new java.awt.Dimension(352, 551));
        wrapCadastrarFornecedor.setMinimumSize(new java.awt.Dimension(352, 551));
        wrapCadastrarFornecedor.setName(""); // NOI18N

        cadastrarFornecedorHeader.setFont(new java.awt.Font("Raleway SemiBold", 0, 16)); // NOI18N
        cadastrarFornecedorHeader.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarFornecedorHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/cadastrarFonecedorHeaderIcon.png"))); // NOI18N
        cadastrarFornecedorHeader.setText("Cadastrar fornecedor");
        cadastrarFornecedorHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cadastrarFornecedorHeaderMouseDragged(evt);
            }
        });
        cadastrarFornecedorHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadastrarFornecedorHeaderMousePressed(evt);
            }
        });

        cadastrarFornecedorCNPJLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        cadastrarFornecedorCNPJLabel.setForeground(new java.awt.Color(31, 31, 31));
        cadastrarFornecedorCNPJLabel.setText("CNPJ:");

        cadastrarFornecedorNomeLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        cadastrarFornecedorNomeLabel.setForeground(new java.awt.Color(31, 31, 31));
        cadastrarFornecedorNomeLabel.setText("Nome:");

        cadastrarFornecedorEmailLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        cadastrarFornecedorEmailLabel.setForeground(new java.awt.Color(31, 31, 31));
        cadastrarFornecedorEmailLabel.setText("Email:");

        cadastrarFornecedorTelefoneLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        cadastrarFornecedorTelefoneLabel.setForeground(new java.awt.Color(31, 31, 31));
        cadastrarFornecedorTelefoneLabel.setText("Telefone:");

        cadastrarFornecedorTelefoneOpcionalLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        cadastrarFornecedorTelefoneOpcionalLabel.setForeground(new java.awt.Color(31, 31, 31));
        cadastrarFornecedorTelefoneOpcionalLabel.setText("Telefone (opcional): ");

        cadastrarFornecedorBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/cancelar.png"))); // NOI18N
        cadastrarFornecedorBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFornecedorBtnCancelarActionPerformed(evt);
            }
        });

        cadastrarFornecedorBtnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/cadastrar.png"))); // NOI18N
        cadastrarFornecedorBtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFornecedorBtnCadastrarActionPerformed(evt);
            }
        });

        try {
            cadastrarFornecedorCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cadastrarFornecedorTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cadastrarFornecedorTelefoneOpcional.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout wrapCadastrarFornecedorLayout = new javax.swing.GroupLayout(wrapCadastrarFornecedor);
        wrapCadastrarFornecedor.setLayout(wrapCadastrarFornecedorLayout);
        wrapCadastrarFornecedorLayout.setHorizontalGroup(
            wrapCadastrarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastrarFornecedorHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addGroup(wrapCadastrarFornecedorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(wrapCadastrarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadastrarFornecedorTelefoneOpcionalLabel)
                    .addComponent(cadastrarFornecedorCNPJLabel)
                    .addComponent(cadastrarFornecedorNomeLabel)
                    .addComponent(cadastrarFornecedorNome)
                    .addComponent(cadastrarFornecedorEmailLabel)
                    .addComponent(cadastrarFornecedorEmail)
                    .addComponent(cadastrarFornecedorTelefoneLabel)
                    .addComponent(cadastrarFornecedorBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(cadastrarFornecedorBtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(cadastrarFornecedorCNPJ)
                    .addComponent(cadastrarFornecedorTelefone)
                    .addComponent(cadastrarFornecedorTelefoneOpcional))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        wrapCadastrarFornecedorLayout.setVerticalGroup(
            wrapCadastrarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapCadastrarFornecedorLayout.createSequentialGroup()
                .addComponent(cadastrarFornecedorHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(cadastrarFornecedorCNPJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarFornecedorCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarFornecedorNomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarFornecedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarFornecedorEmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarFornecedorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarFornecedorTelefoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarFornecedorTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarFornecedorTelefoneOpcionalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarFornecedorTelefoneOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cadastrarFornecedorBtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarFornecedorBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cadastrarFornecedorLayout = new javax.swing.GroupLayout(cadastrarFornecedor.getContentPane());
        cadastrarFornecedor.getContentPane().setLayout(cadastrarFornecedorLayout);
        cadastrarFornecedorLayout.setHorizontalGroup(
            cadastrarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapCadastrarFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cadastrarFornecedorLayout.setVerticalGroup(
            cadastrarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapCadastrarFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(960, 574));
        setUndecorated(true);

        wrap.setBackground(new java.awt.Color(255, 255, 255));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/fechar.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        headerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/headerIcon.png"))); // NOI18N

        headerLabel.setFont(new java.awt.Font("Raleway Medium", 0, 15)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("INVENTARY MANAGER");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnDashboard.png"))); // NOI18N
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnCompras.png"))); // NOI18N
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnProdutos.png"))); // NOI18N
        btnProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btbFornecedoresFocus.png"))); // NOI18N
        btnFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFornecedores)
                    .addComponent(btnCompras)
                    .addComponent(btnDashboard)
                    .addComponent(btnProdutos))
                .addGap(0, 65, Short.MAX_VALUE))
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        fornecedoresLabel.setFont(new java.awt.Font("Raleway", 0, 30)); // NOI18N
        fornecedoresLabel.setForeground(new java.awt.Color(33, 33, 33));
        fornecedoresLabel.setText("Fornecedores");

        fornecedoresDivisor.setForeground(new java.awt.Color(168, 168, 168));

        wrapTableFornecedores.setBackground(new java.awt.Color(255, 255, 255));
        wrapTableFornecedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207)));

        tableFornecedoresLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tableFornecedoresLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/tableComprasHeaderIcon.png"))); // NOI18N
        tableFornecedoresLabel.setText("Fornecedores cadastrados");

        tableFornecedores.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        tableFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CNPJ", "Nome", "Email", "Telefones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFornecedores.setGridColor(new java.awt.Color(255, 255, 255));
        tableFornecedores.setRowHeight(24);
        tableFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFornecedoresMouseClicked(evt);
            }
        });
        scrollTableFornecedores.setViewportView(tableFornecedores);
        if (tableFornecedores.getColumnModel().getColumnCount() > 0) {
            tableFornecedores.getColumnModel().getColumn(0).setResizable(false);
            tableFornecedores.getColumnModel().getColumn(0).setPreferredWidth(150);
        }

        javax.swing.GroupLayout wrapTableFornecedoresLayout = new javax.swing.GroupLayout(wrapTableFornecedores);
        wrapTableFornecedores.setLayout(wrapTableFornecedoresLayout);
        wrapTableFornecedoresLayout.setHorizontalGroup(
            wrapTableFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableFornecedoresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollTableFornecedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        wrapTableFornecedoresLayout.setVerticalGroup(
            wrapTableFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapTableFornecedoresLayout.createSequentialGroup()
                .addComponent(tableFornecedoresLabel)
                .addGap(0, 0, 0)
                .addComponent(scrollTableFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnApagarFornecedor.png"))); // NOI18N
        btnExcluir.setBorder(null);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCadastrarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnCadastrarFornecedor.png"))); // NOI18N
        btnCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFornecedorActionPerformed(evt);
            }
        });

        instructions.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        instructions.setForeground(new java.awt.Color(33, 33, 33));
        instructions.setText("- Lorem");

        pesquisaFornecedores.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        pesquisaFornecedores.setText("Pesquisar");
        pesquisaFornecedores.setMaximumSize(new java.awt.Dimension(400, 40));
        pesquisaFornecedores.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pesquisaFornecedoresCaretUpdate(evt);
            }
        });
        pesquisaFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaFornecedoresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout wrapLayout = new javax.swing.GroupLayout(wrap);
        wrap.setLayout(wrapLayout);
        wrapLayout.setHorizontalGroup(
            wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(wrapLayout.createSequentialGroup()
                .addComponent(sideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addComponent(pesquisaFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addComponent(wrapTableFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fornecedoresDivisor)
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addComponent(fornecedoresLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(instructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        wrapLayout.setVerticalGroup(
            wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(fornecedoresLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fornecedoresDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wrapLayout.createSequentialGroup()
                                .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCadastrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pesquisaFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addComponent(wrapTableFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40))
                            .addGroup(wrapLayout.createSequentialGroup()
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        new Produtos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFornecedorActionPerformed
        cadastrarFornecedor.setResizable(false);
        cadastrarFornecedor.setLocationRelativeTo(null);
        cadastrarFornecedor.setVisible(true);
    }//GEN-LAST:event_btnCadastrarFornecedorActionPerformed

    private void cadastrarFornecedorHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarFornecedorHeaderMousePressed
        this.mouseX = evt.getX();
        this.mouseY = evt.getY();
    }//GEN-LAST:event_cadastrarFornecedorHeaderMousePressed

    private void cadastrarFornecedorHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarFornecedorHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        cadastrarFornecedor.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_cadastrarFornecedorHeaderMouseDragged

    private void cadastrarFornecedorBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFornecedorBtnCancelarActionPerformed
        cadastrarFornecedor.dispose();
    }//GEN-LAST:event_cadastrarFornecedorBtnCancelarActionPerformed

    private void cadastrarFornecedorBtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFornecedorBtnCadastrarActionPerformed
        String nome = cadastrarFornecedorNome.getText();
        String cnpj = cadastrarFornecedorCNPJ.getText();
        String email = cadastrarFornecedorEmail.getText();
        String telefone = cadastrarFornecedorTelefone.getText();
        String tetefoneOpcional = cadastrarFornecedorTelefoneOpcional.getText();
        if (nome.isEmpty() || email.isEmpty() || telefone.isEmpty() || cnpj.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, Preencha os campos!");
        } else {
            new FornecedorDAO().cadastrarFornecedor(cnpj, nome, email, telefone, tetefoneOpcional);
        }
        cadastrarFornecedor.dispose();
        selecionar();
    }//GEN-LAST:event_cadastrarFornecedorBtnCadastrarActionPerformed

    private void tableFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFornecedoresMouseClicked
        if (evt.getClickCount() != 0) {
            selectedRow = tableFornecedores.getSelectedRow();
            if (selectedRow > 0) {
                this.btnExcluir.setVisible(true);
            }
            if (evt.getClickCount() >= 2 || selectedRow > 0) {
                String cnpj = (String)tableFornecedores.getValueAt(selectedRow, 0);
                new DetalharForncedor(cnpj.trim()).setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_tableFornecedoresMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String cnpj = (String) tableFornecedores.getValueAt(selectedRow, 0);
        cnpj = cnpj.trim();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null, "Você realmente deseja deletar este fornecedor? TODAS as compre feitas a esse fornecedor também serão excluídas", "AVISO", dialogButton);
        if (resultado == JOptionPane.YES_OPTION) {
            new FornecedorDAO().deletarFornecedor(cnpj);
            selecionar();
        }

        btnExcluir.setVisible(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void pesquisaFornecedoresCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pesquisaFornecedoresCaretUpdate
        selecionarComRest();
    }//GEN-LAST:event_pesquisaFornecedoresCaretUpdate

    private void pesquisaFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaFornecedoresMouseClicked
        pesquisaFornecedores.setText("");
    }//GEN-LAST:event_pesquisaFornecedoresMouseClicked

    private void selecionar() {
        modelo.setNumRows(0);
        FornecedorDAO fornecedor = new FornecedorDAO();
        for (Fornecedor f : fornecedor.selecionarFornecedores()) {
            modelo.addRow(new Object[]{"  " + f.getCnpj(), "  " + f.getNome(), "  " + f.getEmail(), "  " + new TelefoneFornecedorDAO().selectTelefonesJuntos(f.getCnpj())});
        }
    }

    private void selecionarComRest() {
        modelo.setNumRows(0);
        FornecedorDAO fornecedor = new FornecedorDAO();
        for (Fornecedor f : fornecedor.selecionarFornecedores(pesquisaFornecedores.getText())) {
            modelo.addRow(new Object[]{"  " + f.getCnpj(), "  " + f.getNome(), "  " + f.getEmail(), "  " + new TelefoneFornecedorDAO().selectTelefonesJuntos(f.getCnpj())});
        }
    }

    private void selecionarComString() {

    }

    private void estilizarComponentes() {
        cadastrarFornecedorHeader.setOpaque(true);
        cadastrarFornecedorHeader.setBackground(Color.decode("#27A243"));
        pesquisaFornecedores.setBorder(BorderFactory.createCompoundBorder(pesquisaFornecedores.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        this.setExtendedState(6);
        header.setBackground(Color.decode("#343A40"));
        sideMenu.setBackground(Color.decode("#212529"));
        tableFornecedoresLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("#CFCFCF")));
        tableFornecedoresLabel.setOpaque(true);
        tableFornecedores.setBorder(null);
        scrollTableFornecedores.setBorder(null);
        tableFornecedores.setFillsViewportHeight(true);
        JTableHeader tableFornecedoresHeader = tableFornecedores.getTableHeader();
        tableFornecedoresHeader.setFont((new Font("Raleway SemiBold", 0, 13)));
        instructions.setText("<html><body>- Clique duas vezes em um fornecedor para detalhá-lo.</body></html>");
    }

    private void estilizarBtns() {
        btnDashboard.setOpaque(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setFocusPainted(false);

        btnCompras.setOpaque(false);
        btnCompras.setContentAreaFilled(false);
        btnCompras.setBorderPainted(false);
        btnCompras.setFocusPainted(false);

        btnProdutos.setOpaque(false);
        btnProdutos.setContentAreaFilled(false);
        btnProdutos.setBorderPainted(false);
        btnProdutos.setFocusPainted(false);

        btnFornecedores.setOpaque(false);
        btnFornecedores.setContentAreaFilled(false);
        btnFornecedores.setBorderPainted(false);
        btnFornecedores.setFocusPainted(false);

        btnExcluir.setVisible(false);

        btnCadastrarFornecedor.setFocusPainted(false);
        btnExcluir.setFocusPainted(false);
        btnExit.setFocusPainted(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFornecedor;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JDialog cadastrarFornecedor;
    private javax.swing.JButton cadastrarFornecedorBtnCadastrar;
    private javax.swing.JButton cadastrarFornecedorBtnCancelar;
    private javax.swing.JFormattedTextField cadastrarFornecedorCNPJ;
    private javax.swing.JLabel cadastrarFornecedorCNPJLabel;
    private javax.swing.JTextField cadastrarFornecedorEmail;
    private javax.swing.JLabel cadastrarFornecedorEmailLabel;
    private javax.swing.JLabel cadastrarFornecedorHeader;
    private javax.swing.JTextField cadastrarFornecedorNome;
    private javax.swing.JLabel cadastrarFornecedorNomeLabel;
    private javax.swing.JFormattedTextField cadastrarFornecedorTelefone;
    private javax.swing.JLabel cadastrarFornecedorTelefoneLabel;
    private javax.swing.JFormattedTextField cadastrarFornecedorTelefoneOpcional;
    private javax.swing.JLabel cadastrarFornecedorTelefoneOpcionalLabel;
    private javax.swing.JSeparator fornecedoresDivisor;
    private javax.swing.JLabel fornecedoresLabel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerIcon;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel instructions;
    private javax.swing.JTextField pesquisaFornecedores;
    private javax.swing.JScrollPane scrollTableFornecedores;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JTable tableFornecedores;
    private javax.swing.JLabel tableFornecedoresLabel;
    private javax.swing.JPanel wrap;
    private javax.swing.JPanel wrapCadastrarFornecedor;
    private javax.swing.JPanel wrapTableFornecedores;
    // End of variables declaration//GEN-END:variables
}
