/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrn.gui;

import br.edu.ifrn.negocio.Fornecedor;
import br.edu.ifrn.negocio.Produto;
import br.edu.ifrn.negocio.ProdutoFornecedor;
import br.edu.ifrn.persistencia.FornecedorDAO;
import br.edu.ifrn.persistencia.ProdutoDAO;
import br.edu.ifrn.persistencia.ProdutoFornecedorDAO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.geom.RoundRectangle2D;
import java.math.BigDecimal;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author letic
 */
public class Produtos extends javax.swing.JFrame {

    private DefaultTableModel modeloTableProdutos;
    private DefaultTableModel modeloTablePrecoCompra;
    private DefaultTableModel modeloTableProdutoFornecedores;
    private int mouseX;
    private int mouseY;
    private int selectedRow;
    private boolean edicao;
    private boolean fieldAlteracao;
    private Produto produto;

    public Produtos() {
        initComponents();
        modeloTableProdutos = (DefaultTableModel) tableProdutos.getModel();
        modeloTablePrecoCompra = (DefaultTableModel) tablePrecoCompra.getModel();
        modeloTableProdutoFornecedores = (DefaultTableModel) tableFornecedores.getModel();
        selecionarFornecedores();
        estilizarBtns();
        estilizarComponets();
        selecionarProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarProduto = new javax.swing.JDialog();
        wrapCadastrarProduto = new javax.swing.JPanel();
        cadastrarProdutoHeader = new javax.swing.JLabel();
        cadastrarProdutoCodigoLabel = new javax.swing.JLabel();
        cadastrarProdutoCodigoField = new javax.swing.JTextField();
        cadastrarProdutoNomeLabel = new javax.swing.JLabel();
        cadastrarProdutoNomeField = new javax.swing.JTextField();
        cadastrarProdutoFornecedorLabel = new javax.swing.JLabel();
        scrollTablePrecoCompra = new javax.swing.JScrollPane();
        tablePrecoCompra = new javax.swing.JTable();
        cadastrarProdutoBtnCadastrar = new javax.swing.JButton();
        cadastrarProdutoBtnFechar = new javax.swing.JButton();
        cadastrarProdutoLabel = new javax.swing.JLabel();
        editarProduto = new javax.swing.JDialog();
        wrapCadastrarProduto1 = new javax.swing.JPanel();
        editarProdutoHeader = new javax.swing.JLabel();
        editarProdutoCodigoLabel = new javax.swing.JLabel();
        editarProdutoCodigoField = new javax.swing.JTextField();
        editarProdutoNomeLabel = new javax.swing.JLabel();
        editarProdutoNomeField = new javax.swing.JTextField();
        editarProdutoFornecedoresLabel = new javax.swing.JLabel();
        scrollTableFornecedores = new javax.swing.JScrollPane();
        tableFornecedores = new javax.swing.JTable();
        editarProdutoBtnAtualizar = new javax.swing.JButton();
        editarProdutoBtnFechar = new javax.swing.JButton();
        btnMudarPreco = new javax.swing.JToggleButton();
        btnExcluirFornecedor = new javax.swing.JToggleButton();
        wrap = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        headerIcon = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        sideMenu = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        produtosLabel = new javax.swing.JLabel();
        produtosDivisor = new javax.swing.JSeparator();
        wrapTableProdutos = new javax.swing.JPanel();
        tableProdutosLabel = new javax.swing.JLabel();
        scrollTableProdutos = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();
        instructions = new javax.swing.JLabel();
        pesquisaProdutos = new javax.swing.JTextField();

        cadastrarProduto.setMaximumSize(new java.awt.Dimension(577, 482));
        cadastrarProduto.setMinimumSize(new java.awt.Dimension(577, 482));
        cadastrarProduto.setModal(true);
        cadastrarProduto.setUndecorated(true);
        cadastrarProduto.setPreferredSize(new java.awt.Dimension(577, 482));
        cadastrarProduto.setResizable(false);

        wrapCadastrarProduto.setBackground(new java.awt.Color(255, 255, 255));
        wrapCadastrarProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 162, 67)));
        wrapCadastrarProduto.setMaximumSize(new java.awt.Dimension(577, 440));
        wrapCadastrarProduto.setMinimumSize(new java.awt.Dimension(577, 440));

        cadastrarProdutoHeader.setFont(new java.awt.Font("Raleway SemiBold", 0, 16)); // NOI18N
        cadastrarProdutoHeader.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarProdutoHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/cadastrarProdutoHeaderIcon.png"))); // NOI18N
        cadastrarProdutoHeader.setText("Cadastrar produto");
        cadastrarProdutoHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cadastrarProdutoHeaderMouseDragged(evt);
            }
        });
        cadastrarProdutoHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadastrarProdutoHeaderMousePressed(evt);
            }
        });

        cadastrarProdutoCodigoLabel.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cadastrarProdutoCodigoLabel.setText("Código:");

        cadastrarProdutoCodigoField.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cadastrarProdutoCodigoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastrarProdutoCodigoFieldKeyPressed(evt);
            }
        });

        cadastrarProdutoNomeLabel.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cadastrarProdutoNomeLabel.setText("Nome:");

        cadastrarProdutoNomeField.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N

        cadastrarProdutoFornecedorLabel.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cadastrarProdutoFornecedorLabel.setText("Fornecedores:");

        tablePrecoCompra.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        tablePrecoCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Selecionar", "Fornecedor", "Preço de compra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePrecoCompra.setGridColor(new java.awt.Color(204, 204, 204));
        tablePrecoCompra.setRowHeight(25);
        scrollTablePrecoCompra.setViewportView(tablePrecoCompra);
        if (tablePrecoCompra.getColumnModel().getColumnCount() > 0) {
            tablePrecoCompra.getColumnModel().getColumn(0).setResizable(false);
            tablePrecoCompra.getColumnModel().getColumn(1).setResizable(false);
            tablePrecoCompra.getColumnModel().getColumn(2).setResizable(false);
        }

        cadastrarProdutoBtnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/cPBtnCadastrar.png"))); // NOI18N
        cadastrarProdutoBtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProdutoBtnCadastrarActionPerformed(evt);
            }
        });

        cadastrarProdutoBtnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/cPBtnFechar.png"))); // NOI18N
        cadastrarProdutoBtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProdutoBtnFecharActionPerformed(evt);
            }
        });

        cadastrarProdutoLabel.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N

        javax.swing.GroupLayout wrapCadastrarProdutoLayout = new javax.swing.GroupLayout(wrapCadastrarProduto);
        wrapCadastrarProduto.setLayout(wrapCadastrarProdutoLayout);
        wrapCadastrarProdutoLayout.setHorizontalGroup(
            wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastrarProdutoHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                        .addComponent(cadastrarProdutoBtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(cadastrarProdutoBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cadastrarProdutoFornecedorLabel)
                    .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                        .addGroup(wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastrarProdutoCodigoLabel)
                            .addComponent(cadastrarProdutoCodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastrarProdutoNomeLabel)
                            .addComponent(cadastrarProdutoNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrollTablePrecoCompra)
                    .addComponent(cadastrarProdutoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        wrapCadastrarProdutoLayout.setVerticalGroup(
            wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                .addComponent(cadastrarProdutoHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                        .addComponent(cadastrarProdutoCodigoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarProdutoCodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                        .addComponent(cadastrarProdutoNomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarProdutoNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(cadastrarProdutoFornecedorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarProdutoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTablePrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarProdutoBtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarProdutoBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cadastrarProdutoLayout = new javax.swing.GroupLayout(cadastrarProduto.getContentPane());
        cadastrarProduto.getContentPane().setLayout(cadastrarProdutoLayout);
        cadastrarProdutoLayout.setHorizontalGroup(
            cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        cadastrarProdutoLayout.setVerticalGroup(
            cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        editarProduto.setMaximumSize(new java.awt.Dimension(577, 445));
        editarProduto.setMinimumSize(new java.awt.Dimension(577, 445));
        editarProduto.setModal(true);
        editarProduto.setUndecorated(true);
        editarProduto.setPreferredSize(new java.awt.Dimension(577, 445));

        wrapCadastrarProduto1.setBackground(new java.awt.Color(255, 255, 255));
        wrapCadastrarProduto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 119, 247)));
        wrapCadastrarProduto1.setMaximumSize(new java.awt.Dimension(577, 440));
        wrapCadastrarProduto1.setMinimumSize(new java.awt.Dimension(577, 440));

        editarProdutoHeader.setFont(new java.awt.Font("Raleway SemiBold", 0, 16)); // NOI18N
        editarProdutoHeader.setForeground(new java.awt.Color(255, 255, 255));
        editarProdutoHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/cadastrarProdutoHeaderIcon.png"))); // NOI18N
        editarProdutoHeader.setText("Nome do Produto");
        editarProdutoHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                editarProdutoHeaderMouseDragged(evt);
            }
        });
        editarProdutoHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editarProdutoHeaderMousePressed(evt);
            }
        });

        editarProdutoCodigoLabel.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        editarProdutoCodigoLabel.setText("Código:");

        editarProdutoCodigoField.setEditable(false);
        editarProdutoCodigoField.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N

        editarProdutoNomeLabel.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        editarProdutoNomeLabel.setText("Nome:");

        editarProdutoNomeField.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N

        editarProdutoFornecedoresLabel.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        editarProdutoFornecedoresLabel.setText("Fornecedores:");

        tableFornecedores.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        tableFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Fornecedor", "Preço de compra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFornecedores.setGridColor(new java.awt.Color(204, 204, 204));
        tableFornecedores.setRowHeight(25);
        tableFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFornecedoresMouseClicked(evt);
            }
        });
        scrollTableFornecedores.setViewportView(tableFornecedores);
        if (tableFornecedores.getColumnModel().getColumnCount() > 0) {
            tableFornecedores.getColumnModel().getColumn(0).setResizable(false);
            tableFornecedores.getColumnModel().getColumn(1).setResizable(false);
        }

        editarProdutoBtnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnSalvarAlteracoes.png"))); // NOI18N
        editarProdutoBtnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editarProdutoBtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProdutoBtnAtualizarActionPerformed(evt);
            }
        });

        editarProdutoBtnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/cPBtnFechar.png"))); // NOI18N
        editarProdutoBtnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarProdutoBtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProdutoBtnFecharActionPerformed(evt);
            }
        });

        btnMudarPreco.setText("Mudar preço");

        btnExcluirFornecedor.setText("excluir");

        javax.swing.GroupLayout wrapCadastrarProduto1Layout = new javax.swing.GroupLayout(wrapCadastrarProduto1);
        wrapCadastrarProduto1.setLayout(wrapCadastrarProduto1Layout);
        wrapCadastrarProduto1Layout.setHorizontalGroup(
            wrapCadastrarProduto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarProdutoHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(wrapCadastrarProduto1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(wrapCadastrarProduto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(wrapCadastrarProduto1Layout.createSequentialGroup()
                        .addComponent(editarProdutoBtnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(editarProdutoBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wrapCadastrarProduto1Layout.createSequentialGroup()
                        .addComponent(editarProdutoFornecedoresLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMudarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wrapCadastrarProduto1Layout.createSequentialGroup()
                        .addGroup(wrapCadastrarProduto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarProdutoCodigoLabel)
                            .addComponent(editarProdutoCodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(wrapCadastrarProduto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarProdutoNomeLabel)
                            .addComponent(editarProdutoNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrollTableFornecedores))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        wrapCadastrarProduto1Layout.setVerticalGroup(
            wrapCadastrarProduto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapCadastrarProduto1Layout.createSequentialGroup()
                .addComponent(editarProdutoHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapCadastrarProduto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(wrapCadastrarProduto1Layout.createSequentialGroup()
                        .addComponent(editarProdutoCodigoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarProdutoCodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wrapCadastrarProduto1Layout.createSequentialGroup()
                        .addComponent(editarProdutoNomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarProdutoNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(144, 144, 144)
                .addGroup(wrapCadastrarProduto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarProdutoFornecedoresLabel)
                    .addComponent(btnMudarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTableFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wrapCadastrarProduto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarProdutoBtnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarProdutoBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout editarProdutoLayout = new javax.swing.GroupLayout(editarProduto.getContentPane());
        editarProduto.getContentPane().setLayout(editarProdutoLayout);
        editarProdutoLayout.setHorizontalGroup(
            editarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapCadastrarProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        editarProdutoLayout.setVerticalGroup(
            editarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapCadastrarProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(960, 574));
        setUndecorated(true);

        wrap.setBackground(new java.awt.Color(255, 255, 255));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/fechar.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        headerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/headerIcon.png"))); // NOI18N

        headerLabel.setFont(new java.awt.Font("Raleway Medium", 0, 15)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("INVENTARY MANAGER");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnDashboard.png"))); // NOI18N
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnCompras.png"))); // NOI18N
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnProdutosFocus.png"))); // NOI18N
        btnProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btbFornecedores.png"))); // NOI18N
        btnFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFornecedores)
                    .addComponent(btnCompras)
                    .addComponent(btnDashboard)
                    .addComponent(btnProdutos))
                .addGap(0, 65, Short.MAX_VALUE))
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        produtosLabel.setFont(new java.awt.Font("Raleway", 0, 30)); // NOI18N
        produtosLabel.setForeground(new java.awt.Color(33, 33, 33));
        produtosLabel.setText("Produtos");

        produtosDivisor.setForeground(new java.awt.Color(168, 168, 168));

        wrapTableProdutos.setBackground(new java.awt.Color(255, 255, 255));
        wrapTableProdutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207)));

        tableProdutosLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tableProdutosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/tableComprasHeaderIcon.png"))); // NOI18N
        tableProdutosLabel.setText("Produtos cadastrados");

        tableProdutos.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Fornecedores"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProdutos.setGridColor(new java.awt.Color(255, 255, 255));
        tableProdutos.setRowHeight(25);
        tableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdutosMouseClicked(evt);
            }
        });
        scrollTableProdutos.setViewportView(tableProdutos);
        if (tableProdutos.getColumnModel().getColumnCount() > 0) {
            tableProdutos.getColumnModel().getColumn(0).setPreferredWidth(150);
            tableProdutos.getColumnModel().getColumn(1).setResizable(false);
            tableProdutos.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout wrapTableProdutosLayout = new javax.swing.GroupLayout(wrapTableProdutos);
        wrapTableProdutos.setLayout(wrapTableProdutosLayout);
        wrapTableProdutosLayout.setHorizontalGroup(
            wrapTableProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableProdutosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollTableProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        wrapTableProdutosLayout.setVerticalGroup(
            wrapTableProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapTableProdutosLayout.createSequentialGroup()
                .addComponent(tableProdutosLabel)
                .addGap(0, 0, 0)
                .addComponent(scrollTableProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnExcluir.png"))); // NOI18N
        btnExcluir.setBorder(null);

        btnCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnCadastrarProduto.png"))); // NOI18N
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        instructions.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        instructions.setForeground(new java.awt.Color(33, 33, 33));
        instructions.setText("- Lorem");

        pesquisaProdutos.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        pesquisaProdutos.setText("Pesquisar");
        pesquisaProdutos.setMaximumSize(new java.awt.Dimension(400, 40));
        pesquisaProdutos.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pesquisaProdutosCaretUpdate(evt);
            }
        });
        pesquisaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaProdutosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout wrapLayout = new javax.swing.GroupLayout(wrap);
        wrap.setLayout(wrapLayout);
        wrapLayout.setHorizontalGroup(
            wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(wrapLayout.createSequentialGroup()
                .addComponent(sideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addComponent(pesquisaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addComponent(wrapTableProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(produtosDivisor)
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addComponent(produtosLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(instructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        wrapLayout.setVerticalGroup(
            wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(produtosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produtosDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wrapLayout.createSequentialGroup()
                                .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pesquisaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addComponent(wrapTableProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40))
                            .addGroup(wrapLayout.createSequentialGroup()
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
        new Fornecedores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        cadastrarProduto.setResizable(false);
        cadastrarProduto.setLocationRelativeTo(null);
        cadastrarProduto.setVisible(true);
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void cadastrarProdutoBtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutoBtnFecharActionPerformed
        cadastrarProduto.dispose();
        cadastrarProdutoNomeField.setText(null);
        cadastrarProdutoCodigoField.setText(null);
        selecionarFornecedores();
    }//GEN-LAST:event_cadastrarProdutoBtnFecharActionPerformed

    private void cadastrarProdutoHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProdutoHeaderMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_cadastrarProdutoHeaderMousePressed

    private void cadastrarProdutoHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProdutoHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        cadastrarProduto.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_cadastrarProdutoHeaderMouseDragged

    private void cadastrarProdutoBtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutoBtnCadastrarActionPerformed
        String nome = cadastrarProdutoNomeField.getText();
        String codigo = cadastrarProdutoCodigoField.getText();
        int fornecedorCount = 0;
        int precoVazio = 0;
        if (new ProdutoDAO().verificarCodigo(cadastrarProdutoCodigoField.getText()) != 0) {
            JOptionPane.showMessageDialog(cadastrarProduto, "Este código de barras já foi cadastrado");
            cadastrarProdutoCodigoField.setText("");
        } else if (nome.isEmpty() || codigo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        } else {
            for (int i = 0; i < tablePrecoCompra.getRowCount(); i++) {
                try {
                    if ((boolean) tablePrecoCompra.getValueAt(i, 0)) {
                        fornecedorCount += 1;
                        if (tablePrecoCompra.getValueAt(i, 2) == null) {
                            precoVazio += 1;
                        }
                    }
                } catch (NullPointerException ex) {

                }
            }
            if (fornecedorCount == 0) {
                JOptionPane.showMessageDialog(null, "Selecione pelo menos um fornecedor");
            } else if (precoVazio > 0) {
                JOptionPane.showMessageDialog(null, "Existe(m) algum(ns) campo(s) de preços vazio(s)");
            } else {
                new ProdutoDAO().cadastrarProduto(codigo, nome);
                for (int i = 0; i < tablePrecoCompra.getRowCount(); i++) {
                    try {
                        if ((boolean) tablePrecoCompra.getValueAt(i, 0)) {
                            String cnpjFornecedor = (String) tablePrecoCompra.getValueAt(i, 1);
                            cnpjFornecedor = new FornecedorDAO().nomeParseCnpj(cnpjFornecedor.trim());
                            try {
                                double p = (double) tablePrecoCompra.getValueAt(i, 2);
                                BigDecimal preco = BigDecimal.valueOf(p);
                                new ProdutoFornecedorDAO().cadastrarProdutosFornecedor(codigo, cnpjFornecedor, preco);
                            } catch (NumberFormatException ex) {
                                System.out.println("O preço inserido não segue a formatação correta");
                            }
                        }
                    } catch (NullPointerException ex) {

                    } finally {
                        cadastrarProdutoNomeField.setText(null);
                        cadastrarProdutoCodigoField.setText(null);
                        selecionarFornecedores();
                        selecionarProdutos();
                    }
                }
            }
        }
    }//GEN-LAST:event_cadastrarProdutoBtnCadastrarActionPerformed

    private void cadastrarProdutoCodigoFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastrarProdutoCodigoFieldKeyPressed
        if (evt.getKeyCode() == 10) {
            if (new ProdutoDAO().verificarCodigo(cadastrarProdutoCodigoField.getText()) != 0) {
                cadastrarProdutoCodigoField.setText("");
                JOptionPane.showMessageDialog(cadastrarProduto, "Este código de barras já foi cadastrado");
            } else {
                cadastrarProdutoNomeField.requestFocus();
            }
        }
    }//GEN-LAST:event_cadastrarProdutoCodigoFieldKeyPressed

    private void editarProdutoHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarProdutoHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        editarProduto.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_editarProdutoHeaderMouseDragged

    private void editarProdutoHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarProdutoHeaderMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_editarProdutoHeaderMousePressed

    private void editarProdutoBtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProdutoBtnAtualizarActionPerformed
        System.out.println("Hello, world");
    }//GEN-LAST:event_editarProdutoBtnAtualizarActionPerformed

    private void editarProdutoBtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProdutoBtnFecharActionPerformed
        editarProduto.dispose();
    }//GEN-LAST:event_editarProdutoBtnFecharActionPerformed

    private void tableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutosMouseClicked
        selectedRow = tableProdutos.getSelectedRow();
        if (evt.getClickCount() >= 2 && selectedRow >= 0) {
            this.produto = new ProdutoDAO().getProduto(tableProdutos.getValueAt(selectedRow, 0).toString().trim());
            setFornecedoresProduto(this.produto.getCodigo());
            editarProdutoHeader.setText(this.produto.getNome());
            editarProdutoCodigoField.setText(this.produto.getCodigo());
            editarProdutoNomeField.setText(this.produto.getNome());
            editarProduto.setResizable(false);
            editarProduto.setLocationRelativeTo(null);
            editarProduto.setVisible(true);
        }
    }//GEN-LAST:event_tableProdutosMouseClicked

    private void pesquisaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaProdutosMouseClicked
        pesquisaProdutos.setText("");
    }//GEN-LAST:event_pesquisaProdutosMouseClicked

    private void pesquisaProdutosCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pesquisaProdutosCaretUpdate
        selecionarProdutosComRest();
    }//GEN-LAST:event_pesquisaProdutosCaretUpdate

    private void tableFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFornecedoresMouseClicked
        selectedRow  = tableFornecedores.getSelectedRow();
        if (selectedRow >=0 ) {
            btnExcluirFornecedor.setVisible(true);
            btnMudarPreco.setVisible(true);
        }
    }//GEN-LAST:event_tableFornecedoresMouseClicked

    private void estilizarComponets() {
        header.setBackground(Color.decode("#343A40"));
        sideMenu.setBackground(Color.decode("#212529"));
        cadastrarProdutoHeader.setBackground(Color.decode("#00B050"));
        editarProdutoHeader.setBackground(Color.decode("#0077F7"));
        editarProdutoHeader.setOpaque(true);
        tableProdutosLabel.setOpaque(true);
        cadastrarProdutoHeader.setOpaque(true);
        instructions.setText("<html><body>- Clique duas vezes em um produto para detalhá-lo.</body></html>");
        cadastrarProdutoLabel.setText("<html><body>- É necessário selecionar pelo menos um fornecedor. <br>- Usar ponto (1.99) e não vírgula (1,99) para separar valores decimais.</body></html>");
        tableProdutos.setFillsViewportHeight(true);
        tablePrecoCompra.setFillsViewportHeight(true);
        tableFornecedores.setFillsViewportHeight(true);
        cadastrarProdutoNomeField.setBorder(BorderFactory.createCompoundBorder(cadastrarProdutoNomeField.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        editarProdutoNomeField.setBorder(BorderFactory.createCompoundBorder(editarProdutoNomeField.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        editarProdutoCodigoField.setBorder(BorderFactory.createCompoundBorder(editarProdutoCodigoField.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        cadastrarProdutoCodigoField.setBorder(BorderFactory.createCompoundBorder(cadastrarProdutoCodigoField.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        tableProdutosLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("#CFCFCF")));
        pesquisaProdutos.setBorder(BorderFactory.createCompoundBorder(pesquisaProdutos.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        tableProdutos.setBorder(null);
        scrollTableProdutos.setBorder(null);
        this.setExtendedState(6);
        JTableHeader tablePrecoCompraHeader = tablePrecoCompra.getTableHeader();
        JTableHeader tableProdutosHeader = tableProdutos.getTableHeader();
        JTableHeader tableFornecedoresHeader = tableFornecedores.getTableHeader();
        tableProdutosHeader.setFont((new Font("Raleway SemiBold", 0, 13)));
        tablePrecoCompraHeader.setFont((new Font("Raleway SemiBold", 0, 12)));
        tableFornecedoresHeader.setFont((new Font("Raleway SemiBold", 0, 12)));
    }

    private void estilizarBtns() {
        btnDashboard.setOpaque(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setFocusPainted(false);

        btnCompras.setOpaque(false);
        btnCompras.setContentAreaFilled(false);
        btnCompras.setBorderPainted(false);
        btnCompras.setFocusPainted(false);

        btnProdutos.setOpaque(false);
        btnProdutos.setContentAreaFilled(false);
        btnProdutos.setBorderPainted(false);
        btnProdutos.setFocusPainted(false);

        btnFornecedores.setOpaque(false);
        btnFornecedores.setContentAreaFilled(false);
        btnFornecedores.setBorderPainted(false);
        btnFornecedores.setFocusPainted(false);

        btnExcluir.setVisible(false);
        btnMudarPreco.setVisible(false);
        btnExcluirFornecedor.setVisible(false);

        btnCadastrarProduto.setFocusPainted(false);
        btnExcluir.setFocusPainted(false);
        btnExit.setFocusPainted(false);
        cadastrarProdutoBtnCadastrar.setFocusPainted(false);
        cadastrarProdutoBtnFechar.setFocusPainted(false);
        editarProdutoBtnAtualizar.setFocusPainted(false);
        editarProdutoBtnFechar.setFocusPainted(false);

        editarProdutoBtnAtualizar.setEnabled(false);

        editarProdutoBtnAtualizar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnSalvarAlteracoesDisable.png")));

    }

    private void selecionarFornecedores() {
        int i = 0;
        modeloTablePrecoCompra.setNumRows(0);
        for (Fornecedor f : new FornecedorDAO().selecionarFornecedores()) {
            modeloTablePrecoCompra.addRow(new Object[]{});
            modeloTablePrecoCompra.setValueAt(" " + f.getNome(), i, 1);
            i++;
        }
        tablePrecoCompra.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablePrecoCompra.getColumnModel().getColumn(0).setMinWidth(80);
        tablePrecoCompra.getColumnModel().getColumn(0).setMaxWidth(80);
        tablePrecoCompra.getColumnModel().getColumn(2).setPreferredWidth(130);
        tablePrecoCompra.getColumnModel().getColumn(2).setMinWidth(130);
        tablePrecoCompra.getColumnModel().getColumn(2).setMaxWidth(130);
    }

    private void setFornecedoresProduto(String codigo) {
        modeloTableProdutoFornecedores.setNumRows(0);
        for (ProdutoFornecedor pf : new ProdutoFornecedorDAO().selecionarFornecedoresProduto(codigo)) {
            double precoCompra = pf.getPrecoCompra().doubleValue();
            modeloTableProdutoFornecedores.addRow(new Object[]{" " + pf.getFornecedor().getNome(), precoCompra});
        }
        tableFornecedores.getColumnModel().getColumn(1).setPreferredWidth(110);
        tableFornecedores.getColumnModel().getColumn(1).setMinWidth(110);
        tableFornecedores.getColumnModel().getColumn(1).setMaxWidth(110);
    }

    private void selecionarProdutos() {
        modeloTableProdutos.setNumRows(0);
        for (Produto p : new ProdutoDAO().selecionarProdutos()) {
            modeloTableProdutos.addRow(new Object[]{" " + p.getCodigo(), " " + p.getNome(), " " + new ProdutoFornecedorDAO().getFornecedoresJuntos(p.getCodigo())});
        }
        tableProdutos.getColumnModel().getColumn(0).setPreferredWidth(200);
        tableProdutos.getColumnModel().getColumn(0).setMinWidth(200);
        tableProdutos.getColumnModel().getColumn(0).setMaxWidth(200);
    }

    private void selecionarProdutosComRest() {
        modeloTableProdutos.setNumRows(0);
        for (Produto p : new ProdutoDAO().selecionarProdutos(pesquisaProdutos.getText())) {
            modeloTableProdutos.addRow(new Object[]{" " + p.getCodigo(), " " + p.getNome(), " " + new ProdutoFornecedorDAO().getFornecedoresJuntos(p.getCodigo())});
        }
        tableProdutos.getColumnModel().getColumn(0).setPreferredWidth(300);
        tableProdutos.getColumnModel().getColumn(0).setMinWidth(300);
        tableProdutos.getColumnModel().getColumn(0).setMaxWidth(300);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JToggleButton btnExcluirFornecedor;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JToggleButton btnMudarPreco;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JDialog cadastrarProduto;
    private javax.swing.JButton cadastrarProdutoBtnCadastrar;
    private javax.swing.JButton cadastrarProdutoBtnFechar;
    private javax.swing.JTextField cadastrarProdutoCodigoField;
    private javax.swing.JLabel cadastrarProdutoCodigoLabel;
    private javax.swing.JLabel cadastrarProdutoFornecedorLabel;
    private javax.swing.JLabel cadastrarProdutoHeader;
    private javax.swing.JLabel cadastrarProdutoLabel;
    private javax.swing.JTextField cadastrarProdutoNomeField;
    private javax.swing.JLabel cadastrarProdutoNomeLabel;
    private javax.swing.JDialog editarProduto;
    private javax.swing.JButton editarProdutoBtnAtualizar;
    private javax.swing.JButton editarProdutoBtnFechar;
    private javax.swing.JTextField editarProdutoCodigoField;
    private javax.swing.JLabel editarProdutoCodigoLabel;
    private javax.swing.JLabel editarProdutoFornecedoresLabel;
    private javax.swing.JLabel editarProdutoHeader;
    private javax.swing.JTextField editarProdutoNomeField;
    private javax.swing.JLabel editarProdutoNomeLabel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerIcon;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel instructions;
    private javax.swing.JTextField pesquisaProdutos;
    private javax.swing.JSeparator produtosDivisor;
    private javax.swing.JLabel produtosLabel;
    private javax.swing.JScrollPane scrollTableFornecedores;
    private javax.swing.JScrollPane scrollTablePrecoCompra;
    private javax.swing.JScrollPane scrollTableProdutos;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JTable tableFornecedores;
    private javax.swing.JTable tablePrecoCompra;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JLabel tableProdutosLabel;
    private javax.swing.JPanel wrap;
    private javax.swing.JPanel wrapCadastrarProduto;
    private javax.swing.JPanel wrapCadastrarProduto1;
    private javax.swing.JPanel wrapTableProdutos;
    // End of variables declaration//GEN-END:variables

}
