/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrn.gui;

import br.edu.ifrn.negocio.Fornecedor;
import br.edu.ifrn.persistencia.FornecedorDAO;
import br.edu.ifrn.persistencia.ProdutoDAO;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author letic
 */
public class Produtos extends javax.swing.JFrame {

    DefaultTableModel modeloTableProdutos;
    DefaultTableModel modeloTablePrecoCompra;
    int mouseX;
    int mouseY;

    public Produtos() {
        initComponents();
        modeloTableProdutos = (DefaultTableModel) tableProdutos.getModel();
        modeloTablePrecoCompra = (DefaultTableModel) tablePrecoCompra.getModel();
        selecionarFornecedores();
        estilizarBtns();
        estilizarComponets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarProduto = new javax.swing.JDialog();
        wrapCadastrarProduto = new javax.swing.JPanel();
        cadastrarProdutoHeader = new javax.swing.JLabel();
        cadastrarProdutoCodigoLabel = new javax.swing.JLabel();
        cadastrarProdutoCodigoField = new javax.swing.JTextField();
        cadastrarProdutoNomeLabel = new javax.swing.JLabel();
        cadastrarProdutoNomeField = new javax.swing.JTextField();
        cadastrarProdutoFornecedorLabel = new javax.swing.JLabel();
        scrollTablePrecoCompra = new javax.swing.JScrollPane();
        tablePrecoCompra = new javax.swing.JTable();
        cadastrarProdutoBtnCadastrar = new javax.swing.JButton();
        cadastrarProdutoBtnFechar = new javax.swing.JButton();
        wrap = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        headerIcon = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sideMenu = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        produtosLabel = new javax.swing.JLabel();
        produtosDivisor = new javax.swing.JSeparator();
        wrapTableProdutos = new javax.swing.JPanel();
        tableProdutosLabel = new javax.swing.JLabel();
        scrollTableProdutos = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();
        instructions = new javax.swing.JLabel();
        pesquisaProdutos = new javax.swing.JTextField();

        cadastrarProduto.setMaximumSize(new java.awt.Dimension(577, 440));
        cadastrarProduto.setMinimumSize(new java.awt.Dimension(577, 440));
        cadastrarProduto.setUndecorated(true);
        cadastrarProduto.setPreferredSize(new java.awt.Dimension(577, 440));
        cadastrarProduto.setResizable(false);

        wrapCadastrarProduto.setBackground(new java.awt.Color(255, 255, 255));
        wrapCadastrarProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 162, 67)));
        wrapCadastrarProduto.setMaximumSize(new java.awt.Dimension(577, 440));
        wrapCadastrarProduto.setMinimumSize(new java.awt.Dimension(577, 440));

        cadastrarProdutoHeader.setFont(new java.awt.Font("Raleway SemiBold", 0, 16)); // NOI18N
        cadastrarProdutoHeader.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarProdutoHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/cadastrarProdutoHeaderIcon.png"))); // NOI18N
        cadastrarProdutoHeader.setText("Cadastrar produto");
        cadastrarProdutoHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cadastrarProdutoHeaderMouseDragged(evt);
            }
        });
        cadastrarProdutoHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadastrarProdutoHeaderMousePressed(evt);
            }
        });

        cadastrarProdutoCodigoLabel.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cadastrarProdutoCodigoLabel.setText("Código:");

        cadastrarProdutoNomeLabel.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cadastrarProdutoNomeLabel.setText("Nome:");

        cadastrarProdutoFornecedorLabel.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cadastrarProdutoFornecedorLabel.setText("Fornecedores:");

        tablePrecoCompra.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        tablePrecoCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Selecionar", "Fornecedor", "Preço de compra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePrecoCompra.setGridColor(new java.awt.Color(204, 204, 204));
        tablePrecoCompra.setRowHeight(25);
        scrollTablePrecoCompra.setViewportView(tablePrecoCompra);
        if (tablePrecoCompra.getColumnModel().getColumnCount() > 0) {
            tablePrecoCompra.getColumnModel().getColumn(0).setResizable(false);
            tablePrecoCompra.getColumnModel().getColumn(1).setResizable(false);
            tablePrecoCompra.getColumnModel().getColumn(2).setResizable(false);
        }

        cadastrarProdutoBtnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/cPBtnCadastrar.png"))); // NOI18N
        cadastrarProdutoBtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProdutoBtnCadastrarActionPerformed(evt);
            }
        });

        cadastrarProdutoBtnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/cPBtnFechar.png"))); // NOI18N
        cadastrarProdutoBtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProdutoBtnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wrapCadastrarProdutoLayout = new javax.swing.GroupLayout(wrapCadastrarProduto);
        wrapCadastrarProduto.setLayout(wrapCadastrarProdutoLayout);
        wrapCadastrarProdutoLayout.setHorizontalGroup(
            wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastrarProdutoHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                        .addComponent(cadastrarProdutoBtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(cadastrarProdutoBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cadastrarProdutoFornecedorLabel)
                    .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                        .addGroup(wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastrarProdutoCodigoLabel)
                            .addComponent(cadastrarProdutoCodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastrarProdutoNomeLabel)
                            .addComponent(cadastrarProdutoNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrollTablePrecoCompra))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        wrapCadastrarProdutoLayout.setVerticalGroup(
            wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                .addComponent(cadastrarProdutoHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                        .addComponent(cadastrarProdutoCodigoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarProdutoCodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wrapCadastrarProdutoLayout.createSequentialGroup()
                        .addComponent(cadastrarProdutoNomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarProdutoNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(cadastrarProdutoFornecedorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTablePrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wrapCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarProdutoBtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarProdutoBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cadastrarProdutoLayout = new javax.swing.GroupLayout(cadastrarProduto.getContentPane());
        cadastrarProduto.getContentPane().setLayout(cadastrarProdutoLayout);
        cadastrarProdutoLayout.setHorizontalGroup(
            cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        cadastrarProdutoLayout.setVerticalGroup(
            cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(960, 574));
        setUndecorated(true);

        wrap.setBackground(new java.awt.Color(255, 255, 255));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/fechar.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        headerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/headerIcon.png"))); // NOI18N

        headerLabel.setFont(new java.awt.Font("Raleway Medium", 0, 15)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("INVENTARY MANAGER");

        jButton1.setText("jButton1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerLabel)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerLabel)
                    .addComponent(jLabel2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnDashboard.png"))); // NOI18N
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnCompras.png"))); // NOI18N
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnProdutosFocus.png"))); // NOI18N
        btnProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btbFornecedores.png"))); // NOI18N
        btnFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedoresActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideMenuLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFornecedores)
                            .addComponent(btnCompras)
                            .addComponent(btnDashboard)
                            .addComponent(btnProdutos)))
                    .addGroup(sideMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(0, 65, Short.MAX_VALUE))
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        produtosLabel.setFont(new java.awt.Font("Raleway", 0, 30)); // NOI18N
        produtosLabel.setForeground(new java.awt.Color(33, 33, 33));
        produtosLabel.setText("Produtos");

        produtosDivisor.setForeground(new java.awt.Color(168, 168, 168));

        wrapTableProdutos.setBackground(new java.awt.Color(255, 255, 255));
        wrapTableProdutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207)));

        tableProdutosLabel.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tableProdutosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/tableComprasHeaderIcon.png"))); // NOI18N
        tableProdutosLabel.setText("Produtos cadastrados");

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProdutos.setGridColor(new java.awt.Color(255, 255, 255));
        tableProdutos.setRowHeight(25);
        scrollTableProdutos.setViewportView(tableProdutos);

        javax.swing.GroupLayout wrapTableProdutosLayout = new javax.swing.GroupLayout(wrapTableProdutos);
        wrapTableProdutos.setLayout(wrapTableProdutosLayout);
        wrapTableProdutosLayout.setHorizontalGroup(
            wrapTableProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableProdutosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollTableProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        wrapTableProdutosLayout.setVerticalGroup(
            wrapTableProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapTableProdutosLayout.createSequentialGroup()
                .addComponent(tableProdutosLabel)
                .addGap(0, 0, 0)
                .addComponent(scrollTableProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnExcluir.png"))); // NOI18N
        btnExcluir.setBorder(null);

        btnCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/imgs/btnCadastrarProduto.png"))); // NOI18N
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        instructions.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        instructions.setForeground(new java.awt.Color(33, 33, 33));
        instructions.setText("- Lorem");

        pesquisaProdutos.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        pesquisaProdutos.setText("Pesquisar");
        pesquisaProdutos.setMaximumSize(new java.awt.Dimension(400, 40));

        javax.swing.GroupLayout wrapLayout = new javax.swing.GroupLayout(wrap);
        wrap.setLayout(wrapLayout);
        wrapLayout.setHorizontalGroup(
            wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(wrapLayout.createSequentialGroup()
                .addComponent(sideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addComponent(pesquisaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addComponent(wrapTableProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(produtosDivisor)
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addComponent(produtosLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(instructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        wrapLayout.setVerticalGroup(
            wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(wrapLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(produtosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produtosDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wrapLayout.createSequentialGroup()
                                .addGroup(wrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pesquisaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addComponent(wrapTableProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40))
                            .addGroup(wrapLayout.createSequentialGroup()
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
        new Fornecedores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        cadastrarProduto.setVisible(true);
        cadastrarProduto.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void cadastrarProdutoBtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutoBtnFecharActionPerformed
        cadastrarProduto.dispose();
    }//GEN-LAST:event_cadastrarProdutoBtnFecharActionPerformed

    private void cadastrarProdutoHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProdutoHeaderMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_cadastrarProdutoHeaderMousePressed

    private void cadastrarProdutoHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarProdutoHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        cadastrarProduto.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_cadastrarProdutoHeaderMouseDragged

    private void cadastrarProdutoBtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutoBtnCadastrarActionPerformed
        String nome = cadastrarProdutoNomeField.getText();
        String codigo = cadastrarProdutoCodigoField.getText();

        if (nome.isEmpty() || codigo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        } else {
            for (int i = 0; i < tablePrecoCompra.getRowCount(); i++) {
                try {  
                    if ((boolean) tablePrecoCompra.getValueAt(i, 0)) {
                        
                    }
                } catch (NullPointerException ex) {
                    
                } 
            }
        }
    }//GEN-LAST:event_cadastrarProdutoBtnCadastrarActionPerformed

    private void estilizarComponets() {
        tablePrecoCompra.setFillsViewportHeight(true);
        cadastrarProdutoNomeField.setBorder(BorderFactory.createCompoundBorder(pesquisaProdutos.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        cadastrarProdutoHeader.setBackground(Color.decode("#00B050"));
        cadastrarProdutoCodigoField.setBorder(BorderFactory.createCompoundBorder(pesquisaProdutos.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        cadastrarProdutoHeader.setBackground(Color.decode("#00B050"));
        cadastrarProdutoHeader.setOpaque(true);
        pesquisaProdutos.setBorder(BorderFactory.createCompoundBorder(pesquisaProdutos.getBorder(), BorderFactory.createEmptyBorder(5, 10, 5, 5)));
        this.setExtendedState(6);
        header.setBackground(Color.decode("#343A40"));
        sideMenu.setBackground(Color.decode("#212529"));
        tableProdutosLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("#CFCFCF")));
        tableProdutosLabel.setOpaque(true);
        tableProdutos.setBorder(null);
        scrollTableProdutos.setBorder(null);
        tableProdutos.setFillsViewportHeight(true);
        JTableHeader tableProdutosHeader = tableProdutos.getTableHeader();
        tableProdutosHeader.setFont((new Font("Raleway", 0, 13)));
        JTableHeader tablePrecoCompraHeader = tablePrecoCompra.getTableHeader();
        tablePrecoCompraHeader.setFont((new Font("Raleway", 0, 13)));
        instructions.setText("<html><body>- Clique duas vezes em um produto para alterá-lo.</body></html>");
    }

    private void estilizarBtns() {
        btnDashboard.setOpaque(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setFocusPainted(false);

        btnCompras.setOpaque(false);
        btnCompras.setContentAreaFilled(false);
        btnCompras.setBorderPainted(false);
        btnCompras.setFocusPainted(false);

        btnProdutos.setOpaque(false);
        btnProdutos.setContentAreaFilled(false);
        btnProdutos.setBorderPainted(false);
        btnProdutos.setFocusPainted(false);

        btnFornecedores.setOpaque(false);
        btnFornecedores.setContentAreaFilled(false);
        btnFornecedores.setBorderPainted(false);
        btnFornecedores.setFocusPainted(false);

        btnExcluir.setVisible(false);

        btnCadastrarProduto.setFocusPainted(false);
        btnExcluir.setFocusPainted(false);
        btnExit.setFocusPainted(false);
        cadastrarProdutoBtnCadastrar.setFocusPainted(false);
        cadastrarProdutoBtnFechar.setFocusPainted(false);

    }

    public void selecionarFornecedores() {
        int i = 0;
        modeloTablePrecoCompra.setNumRows(0);
        for (Fornecedor f : new FornecedorDAO().selecionarFornecedores()) {
            modeloTablePrecoCompra.addRow(new Object[]{});
            modeloTablePrecoCompra.setValueAt(" " + f.getNome(), i, 1);
            i++;
        }
        tablePrecoCompra.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablePrecoCompra.getColumnModel().getColumn(0).setMinWidth(80);
        tablePrecoCompra.getColumnModel().getColumn(0).setMaxWidth(80);
        tablePrecoCompra.getColumnModel().getColumn(2).setPreferredWidth(130);
        tablePrecoCompra.getColumnModel().getColumn(2).setMinWidth(130);
        tablePrecoCompra.getColumnModel().getColumn(2).setMaxWidth(130);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JDialog cadastrarProduto;
    private javax.swing.JButton cadastrarProdutoBtnCadastrar;
    private javax.swing.JButton cadastrarProdutoBtnFechar;
    private javax.swing.JTextField cadastrarProdutoCodigoField;
    private javax.swing.JLabel cadastrarProdutoCodigoLabel;
    private javax.swing.JLabel cadastrarProdutoFornecedorLabel;
    private javax.swing.JLabel cadastrarProdutoHeader;
    private javax.swing.JTextField cadastrarProdutoNomeField;
    private javax.swing.JLabel cadastrarProdutoNomeLabel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerIcon;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel instructions;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField pesquisaProdutos;
    private javax.swing.JSeparator produtosDivisor;
    private javax.swing.JLabel produtosLabel;
    private javax.swing.JScrollPane scrollTablePrecoCompra;
    private javax.swing.JScrollPane scrollTableProdutos;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JTable tablePrecoCompra;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JLabel tableProdutosLabel;
    private javax.swing.JPanel wrap;
    private javax.swing.JPanel wrapCadastrarProduto;
    private javax.swing.JPanel wrapTableProdutos;
    // End of variables declaration//GEN-END:variables
}
